name: Continuous Integration

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Build Tools
      run: sudo apt install build-essential
    - name: Install Janet
      run: |
        git clone https://github.com/janet-lang/janet.git /tmp/janet
        cd /tmp/janet
        sudo make all test install
    - name: Build and Install Dependencies
      run: sudo jpm deps
    - name: Run Tests
      run: jpm test
